StatEngine/stat-engine

client/app/reporting/reporting.scss

NOTE: There's still an issue where the entire page scrolls horizontally a little bit unnecessarily. I'll fix that separately.

Fix sidebar overlap in units analysis page.

---

client/app/reporting/reporting.scss
client/themes/bracket-plus/scss/app.scss

I must have gotten a false positive when testing my initial fix for the sidenav overlap issue. There was some extra space on the left when testing on a different computer. It should be consistent now. I also reduced the width of that sidenav a little bit since it didn't need to be so wide.

Proper fix for units sidebar overlap.

---

client/app/app.scss

The labels should be hidden now when the navbar is minimized and reappear if you hover over it or expand it.

Fix floating navbar labels when it's minimized.

---

client/components/auth/router.decorator.js
client/components/modal/modal.service.js
server/api/fire-department/index.js

The user should now get locked out after exceeding the 45 day grace period from when their subscription was canceled. The dialog that shows has a refresh button included so that they don't hit a dead end within the app and can refresh their subscription status without reloading the entire app.
I also updated the warning dialog that shows during the grace period. It should now show a countdown of the days remaining before your service is suspended. It also includes contact info for renewing your subscription.
I'm not sure of any way of easily testing the lockout dialog aside from canceling the subscription and then editing this line in `router.decorator.js` to make it 45 or above...
```javascript
const daysSinceCancellation = moment().diff(canceledAt, 'days');
```

Subscription expired user lockout.

---

client/app/app.scss
client/app/department-admin/department-admin-home/department-admin-home.html
client/app/department-admin/department-admin-home/department-admin-home.scss
client/app/department-admin/department-admin.scss

I removed the **Username** column, grouped actions into a dropdown, and grouped all of the permissions into one column since those were taking up a lot of width. As well as saving space, I think it's actually easier to parse the permissions visually with them grouped. I also tweaked the styling on the status values, since "Pending" was difficult to read as just yellow text.
It should scale to all screen sizes now without any overflow. Emails and names that are too long will get truncated with an ellipsis eventually. It should rarely be an issue except on mid-size widths. However, you can hover over them to see the full value.
It didn't look like there were any actions a user could take on themselves, so I hid the actions dropdown in that case.

Fit "My Departments" page on all screen widths.

---

client/app/incident/incident-search/incident-search.controller.js
client/app/incident/incident-search/incident-search.html
client/app/incident/incident.routes.js
client/components/api/incident.service.js
server/api/incident/incident.controller.js
server/api/incident/index.js

You should now have access to all of the incidents records instead of being limited to 1000, and paging and sorting should now happen server-side. If you run a search, paging and sorting should still function as expected.

Server-side paging and sorting in Incidents page.

---

client/components/incident/incident-map.component.js

Fix incident map default zoom level.

---

client/app/app.js
client/app/app.scss
client/app/incident/incident-search/incident-search.controller.js
client/app/incident/incident-search/incident-search.html
client/app/incident/incident-search/incident-search.scss
client/app/incident/incident.scss
client/components/loading-overlay/loading-overlay.component.html
client/components/loading-overlay/loading-overlay.component.js
client/components/loading-overlay/loading-overlay.scss
client/components/loading-spinner/loading-spinner.component.html
client/components/loading-spinner/loading-spinner.component.js
client/components/loading-spinner/loading-spinner.scss
client/components/on-enter-pressed/onEnterPressed.directive.js
client/components/table-controls/table-controls.component.html
client/components/table-controls/table-controls.component.js
client/components/table-controls/table-controls.scss
server/api/incident/incident.controller.js

Added a custom table view for mobile, custom pagination and sorting controls, as well as loading indicators. The search input should now submit when you press enter with it focused. You should be able to clearly see all data on all screen widths.
For the sake of simplicity, I limited mobile to only sorting by a single column, whereas the desktop view allows you to sort by multiple columns. We could potentially make the mobile sort selector expand dynamically to allow multiple column sorting, but it doesn't seem worth the effort at the moment.

Incidents page responsiveness overhaul.

---

client/components/sidebar/sidebar.component.js

On small screen sizes the navbar should now close automatically after you click on an item in the navbar.

Automatically hide mobile navbar on page change.

---

client/app/app.scss
client/app/incident/incident-search/incident-search.scss

I mainly just made the Incidents table header match the styling of other tables. But I also tweaked the row coloring on tables slightly since before the darker rows matched the background exactly. They're slightly lighter now so that they stand out a bit better from the background. It mainly helps in the mobile view with the cards.

More consistent and improved table styling.

---

client/app/incident/incident-search/incident-search.controller.js

This is probably a better way to accomplish the same thing anyways, since regex is just confusing as hell to look at. You can test to make sure it's working by looking at the **Event Closed** date on the mobile view. It should look the same as in the desktop view.

Fix incompatible regex in Incidents page.

---

client/components/auth/router.decorator.js

The issue with the text is explained here https://github.com/statengine/stat-engine/issues/189

Update misleading text in subscription canceled modal.

---

client/components/chart-table/chart-table.component.js

This fixes issue #194.
I couldn't find any simple way to test this locally without adding a bit of code, but I'm sure it will fix the problem. You can at least verify that it doesn't break the chart though.
The problem was the incident category chart was only calculating the total value the bars scale by on init, so when data would change they would be scaled by the initial total instead of the current total.

Update total value on data change in chart-table component.

---

client/app/reporting/reporting-unit/reporting-unit.html
client/components/bar-gauge/bar-gauge.component.js
client/components/bar-gauge/bar-gauge.html
client/components/bar-gauge/bar-gauge.scss

This should be the proper fix for the bar gauge needles.
I also noticed the needles would sometimes be within one category, but the text would say a different one. It was an issue with the bars all being of equal lengths when the percentile groups weren't exactly equal in length (between their min/max). I made the bars scale a bit more dynamically to exactly match their associated percentile groups. So the needles should essentially be pixel-perfect now when transitioning between categories. They're off by like a pixel right on the edge cases due to some margin weirdness with flexbox, but it didn't seem worth the additional complexity to fix that. It's already obsessively precise enough I think.
I also add a special case for when there's no range between data points, which was causing …

Fix bar gauge needle positioning.

---

client/components/bar-gauge/bar-gauge.component.js
client/components/bar-gauge/bar-gauge.html

The blocks should always be equal sizes now. I went ahead and positioned the needles like you suggested, placing them in the center of the current percentile block. I realized that the min/max isn't technically defined, since the low/high blocks will say "X or less/more" - so there was no clear way to interpolate the needle position within those blocks. I think it looks pretty nice with the needle in the center of the block.

Better fix for bar gauge needle positioning.

---

client/components/auth/router.decorator.js

Global users should no longer see the subscription expiry modals, and should now have full access to the app.

Ignore subscription expiry for global users.

---

client/app/incident/incident-analysis/incident-analysis.html

There were several unused card option buttons that did nothing when clicked. I just went ahead and removed them. There were a few more further down the page that I also removed that aren't shown in the screenshot. I made sure to keep the (i) tooltips where those were used instead of the ellipsis button.

Remove unnecessary card option buttons on Incident Detail page.

---

client/components/incident/incident-timeline.component.js

Changed the "Alarm" row to "Incident" and added a few more timestamps that will show up if data is available or fail silently if not.
Also tweaked existing apparatus timestamp tooltips to use similar casing.

Add more timestamps to Incident Detail page Events Timeline.

---

server/api/email/email.controller.js

This should pass alert border colors to the daily email template along with the background colors. The current `timerange` template should be unaltered with this change in place. The change will only be visible once we copy over the code from the `timerange-test` template into `timerange`.
To test this change in action with the new template, you just need to change the template identifier at line 331 of `email.controller.js` to `timerange-test` and trigger a daily/weekly/monthly email from the `/departmentAdmin/email` page. The new template formatting should work across all screen widths.
Once this PR is approved and merged into master we can copy the `timerange-test` code into `timerange` to make the template updates live.

Email alert style updates.

---

client/app/app.js
client/app/app.scss
client/app/dashboard/dashboard-tenancy/dashboard-tenancy.controller.js
client/app/dashboard/dashboard-tenancy/dashboard-tenancy.html
client/app/dashboard/dashboard-tenancy/dashboard-tenancy.scss
client/app/dashboard/dashboard-tenancy/index.js
client/app/dashboard/dashboard.routes.js
client/app/dashboard/dashboard.scss
client/app/dashboard/index.js
client/app/user/user-home/user-home.controller.js
client/app/user/user-home/user-home.html
client/components/auth/principal.service.js
client/components/sidebar/sidebar.component.js
server/auth/auth.service.js
server/auth/local/index.js
server/kibana/index.js
server/kibana/kibana.settings.js
server/routes.js

In anticipation of multi-tenancy, we need the ability to select a different kibana index (for dashboards, visualizations, etc).  This PR adds a new view to select the tenancy.  
Eventually, users will be able to create new tenants and assign permission/roles to each tenant.  However, I'll add that functionality in another request.  
But to start using the selector, I created a "hard-coded" tenancy for global users.  Global users, will now be able to select their "home" department or a global view.  
All other users will just pass through to kibana (since they just have their default tenancy)

initial multi tenancy to allow global instance

---

server/api/user/index.js
server/api/user/user.controller.js
server/util/async-middleware.js

There was a potential issue where uncaught exceptions within async middleware wouldn't be propagated back to the client, causing the client to hang on an unhandled server error. The error would get logged correctly on the server, but there would be no surrounding try/catch block to send the error back to the client. So this wrapper function serves as a cleaner way of wrapping the entire body of any async middleware with try/catch, sending a 500 status along with the error data to the client if any exceptions are uncaught.
As far as I can tell, this is the cleanest way to safely integrate async/await into node middleware. There doesn't seem to be any built-in system to do this. All of the articles I looked at online regarding this issue are content with manually wrapping the entire body of …

Async middleware wrapper function.

---

server/api/email/email.controller.js

There was an extra `|:` in the regex that shouldn't have been there, which was replacing colons with `, `. I double checked the regex and it should be good now.

Fix regex issue in timerange email notifications.

---

client/app/app.config.js

Apparently the window's inner height doesn't change perfectly in sync with the orientationchange event. So what was happening was the orientation would change and fire a resize event, but when the body was resized to fit the window it would be using the previous orientation's height due to the delay. I grabbed a solution from stackoverflow to detect the moment the window's inner height changes and refit the body at that point. It's a little bit funky, but it works well. Here's the thread on stackoverflow for reference...
https://stackoverflow.com/questions/12452349/mobile-viewport-height-after-orientation-change

Fix mobile body size on orientation change.

---

client/app/account/login/login.html
client/app/account/login/login.scss

This only occurred when testing on an actual mobile device (iPhone 6s for me). The header was also blocking tap events on the "Back" button, so that should be fixed as well now.

Fix high login page header.

---

client/app/app.js
client/app/app.scss
client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/incident/incident-analysis/incident-analysis.html
client/app/incident/incident-analysis/incident-analysis.scss
client/app/reporting/reporting-unit/reporting-unit.controller.js
client/components/incident/incident-alarm-answering-graph.component.js
client/components/incident/incident-alarm-processing-graph.component.js
client/components/incident/incident-comparison-graph.component.js
client/components/incident/incident-timeline.component.js
client/components/incident/incident-unit-response-graph.component.js
client/components/incident/incident-unit-travel-distance-graph.component.js
client/components/incident/incident-unit-travel-duration-graph.component.js
client/components/incident/incident.scss
client/components/print/print.service.js

This should work perfectly in Chrome, and acceptably across all other major browsers. There are a couple known issues when printing from Firefox, Safari, and Edge, but they're relatively minor and extremely difficult to track down, so I think I'll just create tasks for them...
In non-Chrome browsers there's a slight issue with the graphs being a little too wide for their containers. They're still fully visible - they just look a little wonky spilling beyond the border a little on the right side. This seems to be a side-effect of manually sizing the graphs, since they won't seem to automatically resize when rendering the print view despite my best efforts. So, at the moment, I have the sizing and printed page margins hardcoded to look perfect when printing from Chrome at the expense of …

Add print support for Incident Detail page.

---

.babelrc

The app should load in IE11 now. There are a lot of nasty bugs still present in IE11, but the app should at least be functional for the most part.

Fix blank page on IE11.

---

client/app/incident/incident-analysis/incident-analysis.scss

This bug was introduced in the mini-revamp recently.

Fix incident overview top padding on small screens.

---

client/components/appbar/appbar.component.html
client/themes/bracket-plus/scss/app.scss

Fix sign out spacing.

---

client/app/app.scss
client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/incident/incident-analysis/incident-analysis.html
client/app/incident/incident-analysis/incident-analysis.scss
client/app/incident/incident-search/incident-search.html
client/app/incident/incident-search/incident-search.scss
client/app/incident/incident.scss
client/app/reporting/reporting-unit/reporting-unit.html
client/app/reporting/reporting-unit/reporting-unit.scss
client/app/twitter/twitter-home/twitter-home.html
client/app/user/user-home/user-home.html
client/app/user/user-settings/user-settings.html
client/components/incident/incident-alarm-answering-graph.component.js
client/components/incident/incident-alarm-processing-graph.component.js
client/components/incident/incident-comparison-graph.component.js
client/components/incident/incident-unit-response-graph.component.js
client/components/incident/incident-unit-travel-distance-graph.component.js
client/components/incident/incident-unit-travel-duration-graph.component.js
client/components/incidents-table/incidents-table.component.html
client/components/incidents-table/incidents-table.component.js
client/components/incidents-table/incidents-table.scss
client/components/weather/current-weather.component.html
client/components/weather/current-weather.scss
server/api/incident/mapbox.helpers.js

The incident analysis page should be fully responsive now without any breaking UI elements across all screen widths. I also did some general cleanup of element classes for easier maintainability and readability, and tried to move away from bootstrap row/column layouts to allow more flexible css-based layouts and simpler html.
I redid the section nav links (Overview, Location, etc) at the top of the page so that they're no longer tabs (since tabs didn't really make sense there), and so that they match the Units page.
The graph legends have been repositioned to sit on top of each graph, since that's where I generally expect to see them, and since they need to be on top anyways down at mobile screen widths. It also keeps the graphs from getting too squashed when they're positioned side by …

Incident analysis page revamp

---

client/app.template.html
client/app/app.scss

This is a slightly hacky feeling tweak, but as far as I can tell it has no downsides and it works in all major browsers. It fixes an issue that's haunted me ever since the base layout revamp, where sizing page elements with height percentages no longer worked. 
Interestingly, this also fixes an issue where the incidents search table wouldn't resize automatically when shrinking the browser width (expanding worked fine strangely). So it seems to be a healthier layout for preventing downstream glitches.

Base layout tweaks.

---

server/api/user/user.controller.js

These links got committed with localhost addresses somehow, leading production users to a dead end. They should work properly now.
I'll get a better setup for this using development environment settings to avoid the issue in the future.

Fix department access email links.

---

gulpfile.babel.js

The build should be working again with this fix.

Exclude fixture template files in gulp server scripts paths.

---

client/components/sidebar/sidebar.html

**StatEngine** logo is rendered if `vm.theme` attribute is not yet available regardless of its value.
- #142 
- Used `ng-show` directive to display logos only if the `theme` attribute in the `vm` namespace is available due to possible race condition during loading.

additional condition to remove flashing of stat engine logo

---

client/app/user/user-settings/user-settings.html

#234 Issue suggest updating the label to `Repeat New Password` but based on my findings `Retype New Password` conforms more to the current UX standards.
- #234 
- Updated the label based on UX standards

update label for confirm password form element

---

client/components/sidebar/sidebar.html

Dashboard menu item looses the highlighted status when the user clicked anywhere on the screen after navigating to Workspaces.
- #309 
- Added `active` class to **Dashboard** menu item if that's the active navigation route.

add active class to dashboard menu item

---

client/app/reporting/reporting-unit/reporting-unit.controller.js

I used a bit of a hack to fix this. Since the problem was only occurring in Edge it seemed totally possible that it's just some sort of a bug in Edge. So it didn't seem like it was worth spending hours trying to find a "proper" fix since this seems to work just fine.

Fix missing graph in unit timeline in Edge.

---

server/fixtures/templates/visualization/incident-map.json
server/fixtures/templates/visualization/response-map.json

This will cause those maps to automatically default to the department centroid at a zoom level of 12 when the dashboard is first instantiated.

Change response and incident map defaults to department lat/lon

---

client/app/marketplace/marketplace-home/marketplace-home.scss

I just forced each app extension in the list to take up an entire row. Since the page content has a max width now, they never get too ridiculously wide, and this way we've got a bit more space to play with for titles and descriptions.
I also noticed that the featured extension cards and regular extension cards had nearly identical styles, with very subtle differences. So I went ahead and merged their css together.

Fix element truncation in app extension list.

---

client/app/app.scss
client/app/user/user-home/user-home.html
client/app/user/user-home/user-home.scss
client/components/bullet-chart/bullet-chart.component.js
client/components/bullet-chart/bullet-chart.html
client/components/bullet-chart/bullet-chart.scss

I moved the text for the bullet chart above the chart, since fitting them on the same line wasn't feasible due to variable text length.
I also updated the table styling to be consistent with other pages.

Fix bullet charts overflow

---

.babelrc
package-lock.json
package.json

This has just been annoying me slightly for a while to not be able to use the spread operator, so I thought I'd go ahead and add support for it.
Now we can do things like this without getting errors...
```js
const a = { 'a': 1 };
const b = { 'b': 2, ...a };
```

Add spread operator support.

---

client/app/user/user-home/user-home.html
client/components/navbar/navbar.component.js
client/components/navbar/navbar.html
client/components/sidebar/sidebar.component.js
client/components/sidebar/sidebar.html

All "Dashboard" items should now say "Workspaces".
I also changed "Dashboard" to "Workspaces" in all of the Amplitude events, to avoid confusion. I guess that'll probably break tracking consistency for a little bit though... let me know if you don't think that change is worth it.
I also updated the sidebar icon, changing it from the dial to a bar chart in order to be more consistent with the action icon in the control center. I think it looks a little better than the dial as well.

Change "Dashboard" menu items to "Workspaces".

---

.gitignore
Makefile

We used to store our makefiles in a separate devops repo, but due to some changes in the way we run the build jobs, we need to keep the Makefiles with the application code.  It also makes more sense to me to keep the Makefile in this repo.

Add makefile to repo

---

.github/CODE_OF_CONDUCT.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Issue and Pull Request templates should be introduced to the project in order to help maintain consistency in defining features and bugs.
- #382 
Please add or remove lines from the proposed templates if need be.

add github templates to the project

---

server/api/incident/incident.js

NFPA engine travel times should include quints and ladders, which also provide suppression capabilities.  
Customer reported
The NFPA fields are phased for deprecation, so I updated the field references.  
N/A
Navigate to: http://localhost:3000/incidents/F01812310077.
First engine travel time should reflect E14s travel time

Quints are engines

---

client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/incident/incident-analysis/incident-analysis.html
client/app/incident/incident.routes.js

The Incidents Analysis page was essentially timing out during initialization, since it was using `async $onInit()` which doesn't seem to be properly supported by AngularJS. So Angular was ignoring the fact that `vm.initialized` had been set to true and not rendering the page.
- #398 
- Moved module lazy loading to Incident Analysis page route resolvers.
- Removed `ng-if="vm.initialized"` from root element in Incident Analysis page.
- In `master` branch, add the following code to the start of `$onInit()` in `incident.analysis.controller.js`:
```js
await new Promise(resolve => {
setTimeout(resolve, 3000);
});
```
- With caching disabled, navigate to the Incident Analysis page. It should show a blank white page even after the 3 seconds have passed.
- In `fix-incident-white-page` branch, add …

Fix incidents analysis white page on first load.

---

server/routes.js

K8S needs a GET endpoint to check for readiness.  
none
- Changed POST heartbeat endpoint to a GET 
none
- GET localhost:3000/heartbeat returns 204

change heartbeat endpoint to GET

---

server/api/user/user.model.js
server/app.js

Attempting to sign up using the same email with different casing should now fail.
I added the `babel-polyfill` import to `app.js` so that using `async/await` doesn't throw a regenerator runtime error.

Case-insensitive unique email validation.

---

server/api/user/user.model.js

User email should only be validated when the account is being created.
- #407 
- Guarded user email validation with check against sequelize's `this.isNewRecord` field
- Create new user account
- Login as department admin for the new user's requested department
- Approve user
- User should be approved with no errors

Only validate user email on create.

---

client/components/footer/footer.html

The copyright section in the Footer should be center-aligned in all resolutions.
- #389 
- Applied margin-right on the footer
- Load Landing page
- Scroll all the way down to the bottom
- Change around the size of the browser window

apply auto margin for both sides

---

client/app/incident/incident-search/incident-search.controller.js
client/app/incident/incident-search/incident-search.html
client/app/incident/incident-search/incident-search.scss
client/app/incident/incident.routes.js
server/api/incident/incident.controller.js

Add two fields to search by, startDate and endDate.
- #404 
- Added TimePicker and DatePicker component pairs to form a time range input
- Hooked these components with the corresponding controller in the scope
- Added logic to filter out incidents that occurred outside of the given time window
- Go to `incidents/search` page
- Fill up the range components
- Check whether the results are in the given time window
Based on a chat with @bingles a more UX friendly widget may be used where the Time and Date picker inputs are put together in the same popup.

add filter inputs to incidents

---

client/components/incidents-table/incidents-table.component.html
client/components/table-controls/table-controls.component.js

Only show up to 10 pages of incidents in the Incidents page table. This is to fix a rendering speed issue for departments with hundreds or thousands of pages of incidents. Elasticsearch also limits paging to 10,000 results, which makes a large number of pages impossible anyways.
- #422 
- Added `max-pages` attribute to `table-controls` component.
- Set Incidents page `table-controls` elements' `max-pages` to 10.
- Login with a department that has hundreds of thousands of incidents.
- Navigate to Incidents page.
- Page should load quickly and pages should be limited to 10.

Limit incidents page table to 10 pages.

---

server/config/seedDev.js

This is just a minor workflow improvement. Anytime I've wanted to switch to a branch with a schema change I've been having to edit `app.js` and set the database sync to forced, then run the app, then revert `app.js`. This just lets you run the `seed:dev` gulp task to sync your schema.

Force sync database schema on seed dev.

---

client/app/incident/incident-analysis/incident-analysis.html
client/components/weather/current-weather.component.html
server/api/incident/incident.helpers.js
server/api/third-party/first-arriving/first-arriving.controller.js
server/api/third-party/first-arriving/index.js
server/api/third-party/index.js
server/routes.js
server/util/statistics.js

First Arriving API endpoints can now be accessed at `/api/third-party/first-arriving`. Here are each of the views and their endpoints:
**Incident Analysis**
`/api/third-party/first-arriving/incident-analysis`
**Unit Utilization**
`/api/third-party/first-arriving/unit-utilization`
**Turnout Leaderboard**
`/api/third-party/first-arriving/turnout-leaderboard`
- #425 
- Added `/api/third-party` route for grouping endpoints by organization for external projects.
- Added `/api/third-party/first-arriving` route for First Arriving endpoints.
- Added endpoints for each First Arriving view.
- Updated `generateTextualSummaries()` to use snake case keys instead of camel case, and updated UI to use the new key names.
- Added `statistics.js` file on server with unit quintile and busyness calculations. …

First Arriving API

---

client/components/reporting-unit-list/reporting-unit-list.component.js
client/components/reporting-unit-list/reporting-unit-list.html
client/components/reporting-unit-list/reporting-unit-list.scss

Adds radio buttons to sort filtered units alphabetically or by total responses
- #343 
- Added UI element to sort via angular filter using a property variable thats set from radio button.
- Open StatEngine
- Login
- Click Units under reports
- Click a sort order

Sort Units Alphabetically

---

client/components/bullet-chart/bullet-chart.component.js

Code was double importing plotly which created a massive bundle so we improved the imports to only import whats used.
- #403
- Changed dynamic import to use specific modules
- Run app
- Ensure apps still run
- Inspect bundle size in localhost:8888 or through network tab on Developer tools in Chrome.

Optimize Plotly

---

client/app/app.scss
client/app/user/user-home/user-home.html

Add empty states to recap component
- #366 
- Empty state HTML
- Login

Recap Empty States

---

client/components/chart/incident-apparatus-timeline.component.js
client/components/chart/incident-apparatus-timeline.html

Added Ability to sort timeline by response time and incident number
- #295 
- UI to sort
- Sort logic
- Login
- Click Units under Reports
- Click a unit that has data
- Click on timeline tab
- Change sort by

Event Timeline Sort

---

client/app/admin/fire-department/fire-department.controller.js

Logo wasn't being attached to fire department after upload
- #473 
- Added logic to attach logo to fire department object
N/A
- Update or create a fire department at /admin and ensure the logo attaches and persists on the department

Fire Department update and create logo fix

---

client/app/incident/incident-analysis/incident-analysis.html

Added empty state to incident analysis page for units & personnel where units array is empty
- #477 
- Added view logic
- Find Incident with 0 units
- Should see empty state

Added empty state to unit & personnel block on incident analysis page

---

client/app/incident/incident-search/incident-search.controller.js
client/components/incidents-table/incidents-table.component.js
client/components/logo/logo.component.js

Pretty straightforward... however, with the addition of this column, the dates started getting truncated on mid-size screen widths. So I used a more condensed date format between 1200px and 1500px screen widths. I also added tooltips for all of the columns, since they'll be truncated more easily now.
- #493 
- Updated `incidents-table` component to include "Event Opened" column
- Added tooltips to `incidents-table` columns
- Shortened `incidents-table` dates on mid-size screens

Add "Event Opened" column in incidents search

---

client/app/app.scss
client/app/effective-response-force/effective-response-force.routes.js
client/app/incident/incident-analysis/incident-analysis.html
client/app/incident/incident-analysis/incident-analysis.scss
client/app/incident/incident.routes.js
client/app/moveup/moveup-home/moveup-home.controller.js
client/components/incident/incident-map.component.js
client/components/incident/incident-map.html
client/components/incident/incident-map.scss
client/components/incident/index.js
client/util/imports.js
server/api/incident/incident.controller.js

Added ability to toggle concurrent incidents on map inside Incident analysis view
-  #481 
- N/A
- Find incident in incident analysis with concurrent incidents
- Scroll to Map
- Click Layer button to toggle them on
- Search around map to find concurrent incidents

Concurrent Incidents

---

client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/incident/incident-analysis/incident-analysis.html

On Incident report: if the subtype is empty, do not display
- https://app.asana.com/0/1192964035696480/1197938883939891
-
-

fix(incidentAnalysis): hide subtype if empty

---

client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/user/user-home/user-home.controller.js

Currently when you change department it logs you out inorder to switch departments which is very annoying. I removed the logout logic and reload the state to reflect the new department.
- https://app.asana.com/0/1179442471684209/1199234262709937/f
- Changed setFireDepartment function 
-

Fixed the setFireDepartment function to remove logout and reload state

---

package-lock.json

This bug may resurface, because it appears one or more transitive dependencies use `git+ssh` urls in dependency lists.

Fixes instances of git+ssh urls since there are no ssh keys inside the docker container.
