client/_index.html
client/app/account/index.js
client/app/account/login/index.js
client/app/account/settings/index.js
client/app/account/signup/index.js
client/app/admin/index.js
client/app/app.constants.js
client/app/app.js
client/app/app.scss
client/app/legal/index.js
client/app/legal/legal.routes.js
client/app/legal/terms-of-use/index.js
client/app/legal/terms-of-use/terms-of-use.html
client/app/main/main.component.js
client/components/auth/auth.module.js
client/components/footer/footer.html
client/components/modal/modal.service.js
client/components/mongoose-error/mongoose-error.directive.js
client/components/oauth-buttons/index.js
client/components/socket/socket.service.js
client/components/util/util.module.js

added terms of use

---

client/_index.html
client/app/account/login/login.html
client/app/account/login/login.scss
client/app/account/signup/signup.html
client/app/account/signup/signup.scss
client/app/app.scss
client/app/main/main.html

The styles of the login and signup page was annoying me a bit with the footer and no navbar, so I made it much simpler, like the old kibana styles. 
What do you guys think?

updated login and signup page

---

client/app/user/user-home/user-home.controller.js
client/app/user/user-home/user-home.html
server/api/fire-department/fire-department.model.js
server/auth/local/index.js
sql/base.sql

SQL to run for existing:
```
alter table "FireDepartments" add column integration_complete BOOLEAN DEFAULT FALSE;
alter table "FireDepartments" add column integration_verified BOOLEAN DEFAULT FALSE;
```

Getting started information.

---

server/api/user/user.controller.js

Casing should now be ignored in the password reset email.

Case insensitive password reset.

---

client/app/account/resetpassword/resetpass.controller.js
client/app/account/resetpassword/resetpass.html

You should see an alert pop up after a password reset email was successfully sent. The button will return you to the **Sign In** page. Clicking the X button or the background will just dismiss the alert.

Reset password alert.

---

client/app/department-admin/department-admin-home/department-admin-home.html
client/app/department-admin/department-admin-home/department-admin-home.scss

Show Username column in Department Users table.

---

client/components/weather/current-weather.component.html

Fix precipitation label in user home weather.

---

client/app/account/account.routes.js
client/app/account/forgot-username/forgot-username.controller.js
client/app/account/forgot-username/forgot-username.html
client/app/account/forgot-username/index.js
client/app/account/index.js
client/app/account/login/login.html
client/components/api/user.service.js
server/api/user/index.js
server/api/user/user.controller.js
server/config/environment/index.js

Added a flow that works just like resetting your password, except you receive your username in an email instead of a reset link.

Allow users to request their username.

---

client/components/sidebar/sidebar.html

Use hamburger icon for mobile menu button.

---

client/components/rank/rank.component.js

Ranks should update properly now when data changes without requiring a page refresh.

Respond to data changes in rank component.

---

client/components/percent-change/percent-change.component.js
client/components/percent-change/percent-change.html

Percent change pills should respond to data updates now without having to reload the page. I also added comma number grouping for them.

Respond to data changes in percent-change component.

---

client/components/sidebar/sidebar.html

Fix missing sub-item highlight in sidenav.

---

client/app/incident/incident-search/incident-search.controller.js
client/components/incidents-table/incidents-table.component.js

Should be back in working order on Safari and iPhone now.

Fix regex issue again.

---

client/app/reporting/reporting-unit/reporting-unit.html
client/app/reporting/reporting-unit/reporting-unit.scss
client/components/percent-change/percent-change.html
client/components/percent-change/percent-change.scss

Fix percent-change styling.

---

client/app/incident/incident-analysis/incident-analysis.controller.js

Tooltips should be shown with a slide/fade animation now instead of the bounce animation.

Tweak animation for tooltips in Incident Detail page.

---

server/api/fire-department/fire-department.controller.js
server/api/user/user.controller.js
server/util/error.js

I extracted the `validationError()` and `handleError()` functions into a reusable module (with logging added), since they were declared identically in two places.

Fix missing error logging on server.

---

client/components/sidebar/sidebar.html

Update docs link.

---

client/app/department-admin/department-admin-email/department-admin-email.html

I know this is a hidden page, but it was a simple fix and I feel much less dirty using it now.

Fix formatting on department admin email page.

---

client/app/app.scss

This fixes the horizontal scroll issue on the department admin email page. It also potentially fixes similar issues that could have arisen with usage of the 'container' class in the new base layout.

Fix overscrolling in department admin email page.

---

client/components/footer/footer.html

Fix "Company" styling in footer.

---

client/app/app.js
client/components/chart/incident-apparatus-timeline.component.js
package-lock.json
package.json

For some reason these links were only getting selected on mobile when you would tap them. The issue only occurs on actual mobile devices. Setting up events on the link elements seemed to fix the problem though. I included the HammerJS library to properly register tap events on mobile devices.

Fix incident links in Units -> Timeline on mobile.

---

server/api/email/email.controller.js
server/config/seed.js

FYI.  Emails were failing for mailing list customers (someone just let me know today).
Going to merge now.

fix emails for mailing list

---

client/app/app.scss
client/app/main/main.scss
client/app/main/main/main.html
client/components/navbar/navbar.html
client/components/navbar/navbar.scss

I fixed the navbar links, which weren't acting like a row in IE. I tried to fix the wave on IE, but was having difficulty getting it to position consistently across screen widths. I was also having trouble giving it a drop shadow, so I just went ahead and replaced it with a box on IE, which I think looks fine.
In the process, I also noticed that the navbar links weren't quite centered with the logo. So that'll be fixed across all browsers now.

IE landing page fixes

---

client/app/app.scss
client/app/incident/incident-analysis/incident-analysis.html
client/app/incident/incident-search/incident-search.html
client/app/marketplace/application-install/application-install.html
client/app/marketplace/extension-request/extension-request.html
client/app/reporting/reporting-unit/reporting-unit.html
client/app/workspace/workspace-edit/workspace-edit.html
client/app/workspace/workspace-select/workspace-select.html
client/components/breadcrumbs/breadcrumbs.scss

I just moved styling to the `.breadcrumb` class to avoid potential style inconsistencies.

Standardize breadcrumb styling.

---

server/api/user/user.controller.js

@andersonad thanks for reporting.

filter out deleted workspaces for global users

---

client/app/account/signup/signup.html
client/app/admin/user/user.html
client/app/user/user-home/user-home.html

- #277 
- Augmented the labels of the department list with the corresponding state code to distinguish departments with duplicate names.

extend department list with state code

---

client/components/navbar/navbar.html
client/components/navbar/navbar.scss

- #229 
- Applied markup and styles to add dropdown functionality to principal navbar element

add dropdown to navigation bar

---

client/components/chart/incident-travel-category-chart.component.js
client/components/chart/incident-turnout-category-chart.component.js

Fix unit report turnout and travel time graphs

---

client/app/incident/incident-analysis/incident-analysis.controller.js
client/components/navbar/navbar.component.js

Fix scroll-to buttons.

---

client/app/marketplace/extension-request/extension-request.html

Fix app extension header alignment.

---

client/app/user/user-home/user-home.html

I gave the button some margin, and also gave the whole "switch department" section a little space at the top and left aligned the warning text.

Styling tweaks for Switch Department in Control Center.

---

client/app/user/user-home/user-home.html

Just removed the "more" from "more busier"

Fix typo in user home "units" section.

---

client/components/navbar/navbar.component.js
client/components/navbar/navbar.html

Close navbar dropdowns when clicking anywhere.

---

client/app/marketplace/marketplace-home/marketplace-home.html
client/app/marketplace/marketplace-home/marketplace-home.scss

Just mainly made the icons fill the cards, but also did some html/css cleanup and organization.

Extension card polish.

---

client/app/marketplace/marketplace-home/marketplace-home.html
client/app/marketplace/marketplace-home/marketplace-home.scss

Underline selected category in Marketplace.

---

package-lock.json
package.json

Looks like this made it into the package accidentally. It was giving me an error when running `npm ci` that save-dev@2.0.0 doesn't exist.
https://www.npmjs.com/package/save-dev

Remove save-dev from package.json.

---

client/app/app.js
client/app/user/help/help-home.html
client/app/user/index.js
client/components/footer/footer.component.js
client/components/footer/footer.html
client/components/sidebar/sidebar.html
gulpfile.babel.js

This PR was branched off the HelpLinks branch, so please see that PR first. 
For debugging purposes, it would be nice to see what version of the build is running, so I added an environment variable to footer.
In the build process, this will be set to the Docker Image Tag.

Add build version

---

webpack.make.js

Webpack Analyzer opens whenever a code change is made

---

client/app/report/report-view/report-view.controller.js
client/components/auth/router.decorator.js
client/components/helpers/timelineUtils.js
client/components/shift/shift.component.js
package-lock.json
package.json
server/api/effective-response-force/effective-response-force.controller.js
server/api/incident/analysis-rules/FirstUnitDueShouldArriveFirst.js
server/api/incident/incident.controller.js
server/api/incident/incident.js
server/api/report/report.controller.js
server/api/weather/weather.controller.js
server/lib/timeRangeUtils.js
server/lib/timeRangeUtils.spec.js

I noticed that `moment-timezone` was being imported in many places without us having an actual dependency on it in our `package.json`. The dependency must have been satisfied indirectly by another package. And in several places `moment` was being imported but features from `moment-timezone` were being used. So I replaced our `moment` dependency with `moment-timezone` (`moment` is included in it) and replace all `moment` imports with `moment-timezone` imports.
- Removed `moment` dependency
- Added `moment-timezone` dependency
- Changed `moment` imports to `moment-timezone`

Proper dependency and imports for moment-timezone.

---

server/api/workspace/workspace.controller.js
server/api/workspace/workspace.model.js

Global and admin users cannot edit or delete workspaces.  
Login as admin and try to delete a workspace.  
Login as admin and try to edit an existing workspace.
-
-
-

fix workspace permissions

---

server/api/email/email.controller.js
server/lib/incidentAnalysisTimeRange.js
server/lib/rules/eventDurationSumRule.js
server/lib/rules/fireIncidentEventDurationRule30.js
server/lib/rules/fireIncidentEventDurationRule60.js
server/lib/rules/overnightEventsRule.js
server/lib/rules/travelDurationOutlierRule.js
server/lib/rules/turnoutDurationOutlierRule.js
server/lib/rules/turnoutDurationOutlierRule120.js

add turnout rule for 120 sec

---

server/api/third-party/first-arriving/first-arriving.controller.js

fix first arriving

---

client/app/effective-response-force/effective-response-force-analysis/effective-response-force-analysis.controller.js
client/app/effective-response-force/effective-response-force-analysis/effective-response-force-analysis.html
server/api/effective-response-force/effective-response-force.controller.js

add years and all filters to erf tool

---

README.md
client/app/app.js
client/app/app.scss
client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/incident/incident-analysis/incident-analysis.html
client/app/notify/notification.controller.js
client/app/notify/notification.html
client/components/api/api.module.js
client/components/api/notification.service.js
client/themes/bracket-plus/scss/util/_misc.scss
package-lock.json
package.json
server/api/notify/index.js
server/api/notify/notify.controller.js
server/routes.js

- Adds UI button to Incident report page that opens a modal to notify users.
- Adds Proxy endpoint to authenticate NFORS and forward payload to authenticated NFORS endpoint
- #438
- Updated Readme with additional requirement details
- Added UI button to Incident report page
- Added proxy endpoint to proxy NFORS with authentication
- To be determined

Notification UI

---

server/api/notify/notify.controller.js

Improved error handling so we can debug notification issues easier
- N/A
- Changed notify endpoint to return more information
N/A
- N/A

Improved notify error handling

---

client/app/incident/incident-search/incident-search.html
client/app/incident/incident-search/incident-search.scss

When the view goes less than 1200px in width, the filters squish and go on separate lines so I improved
- #418 
- Changed DOM structure a bit and added a media query to change the behavior at the troubled viewport sizes
- Login
- View `/incidents/search`
- Resize window from big to small

Incident Small Viewport Improvement

---

client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/notify/notification.controller.js

Added amplitude event for notifcations
- #447 
- Added event and dependencies
n/a
- n/a

Added amplitude event for notifications

---

client/app/app.js
client/app/app.scss
client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/notify/notification.controller.js
client/app/notify/notification.html
client/app/notify/notification.scss
client/components/api/unit.service.js
client/components/auto-complete/auto-complete.component.js
client/components/auto-complete/auto-complete.html
client/components/auto-complete/auto-complete.scss
client/components/tree-select/tree-select.component.js
client/components/tree-select/tree-select.html
client/components/tree-select/tree-select.scss
package-lock.json
package.json
server/api/personnel/index.js
server/api/personnel/personnel.controller.js
server/api/units/index.js
server/api/units/unit-metrics.controller.js
server/routes.js

Added personnel to units dropdown
- #451
- #453 
- HTML structure
- Login
- Go to incident report
- Click a report
- Click "Notify Exposure"

Notification Modal Feedback

---

client/app/notify/notification.controller.js
client/app/notify/notification.html
client/components/auto-complete/auto-complete.component.js
client/components/auto-complete/auto-complete.html
client/components/tree-select/tree-select.component.js
client/components/tree-select/tree-select.html
server/api/personnel/personnel.controller.js

Implemented more feedback from email threads.
- N/A
- Removed character limit in textfield
- Improved autocomplete
- Fixed typo causing payload to fail
- Improved tree-select
N / A
N /A

Notification Bugfixes & Feedback

---

client/app/notify/notification.controller.js
client/components/auto-complete/auto-complete.component.js

Removed any assumption of type integer
- N/A
- Removed casts to integer
N/A
- N/A

Notification Assumption Fix

---

client/app/notify/notification.controller.js
server/api/personnel/personnel.controller.js

Made minor improvements to notifications UI
- N/A
- Made search not care about case
- Fixed console error
- Improved error handling
N/A
- N/A

Small Notification Improvements

---

client/app/notify/notification.controller.js
client/app/notify/notification.html

- Fixes If no apparatuses are found the notification modal doesn't work as the constructor errors out.
- Fixes bug If you select / deselect personnel, it still sends notification
- N/A
- Added check for apparatus and copy to prompt user to use manual entry if it doesn't exist
- Fixed edge case where if you deselect a personnel it still sends a notification for them
N/A
- N/A

Notification Edge case fixes

---

client/app/moveup/move-up.routes.js
client/components/move-up-map/move-up-map.scss
server/api/incident/incident.controller.js

Resolved issues that I noticed from Production
- N/A
- Changed get incident query to be able to pass a source
N/A
- Click applications
- Click move up model

Move-up Model Improvements

---

client/components/move-up-map/move-up-map.scss

- Changed path to hopefully get picked up by webpack
- N/A
- N/A
N/A
- N/A

Missing SVG fix

---

client/app/admin/fire-department/fire-department.controller.js
client/app/admin/fire-department/fire-department.html
server/api/fire-department/fire-department.controller.js

Currently when you upload a photo in the fire department creation flow it uploads before the fire department is created so the upload endpoint 404's.
- #415 
- Changed fire department creation endpoint to return fire department
- Changed image upload to happen after fire department is created
N/A
- Login to admin account
- Go to create department flow
- Complete form and upload image

Resolved Logo upload bug

---

client/app.template.html
client/app/app.config.js
client/app/app.js
client/app/app.scss
client/components/auth/principal.service.js
client/components/auth/router.decorator.js
client/components/subscription-banner/subscription-banner.component.js
client/components/subscription-banner/subscription-banner.html
client/components/subscription-banner/subscription-banner.scss

Add a banner at the top of the screen to alert users that there subscription is expiring soon.
- #222 
- Implemented banner component
- Added subscription to Principle service
- Login to account that is admin department
- Cancel subscription if active

Subscription Banner

---

server/api/notify/notify.controller.js

Removes await on notification as the notification takes along time. We want the UX to be snappy. If the notification fails, we log and fallback to email.
- N/A
- N/A
N/A
- N/A

Snappy Notifications

---

client/app/incident/incident-analysis/incident-analysis.controller.js
client/app/incident/incident-analysis/incident-analysis.html
client/app/incident/incident-analysis/incident-analysis.scss

Added a list for the units & personnel to analysis page
- #467 
- Added personnel and units block
- Changed styles of response overview block
- Click on incident report
- Scroll down

Units & Personnel in Incident Analysis

---

client/app/admin/fire-department/fire-department.controller.js

Wraps upload api in a promise to properly return URI
-N/A
- Wrapped upload in promise
N/A
- N/A

Return URL properly from promise

---

client/app/moveup/move-up.routes.js
client/app/moveup/moveup-home/moveup-home.controller.js
client/app/moveup/moveup-home/moveup-home.html
client/app/moveup/moveup-home/moveup-home.scss
client/components/api/fire-department.service.js
client/components/move-up-map/move-up-map.component.js
server/api/fire-department/fire-department.controller.js
server/api/fire-department/index.js

Additional feedback
- #489 
- #488 
- #486 
- #485 
- #483 
- #482
- #487 
- N/A
N/A
- N/A
⭐ This branch requires an additional environment variable to be added. DM me for details ⭐

Move Up Model Feedback #2

---

server/api/third-party/first-arriving/first-arriving.controller.js

Switch UHU from using the shift/week/etc in calculations to using the current one, with calculations up to the second.
- #495 
- Modified `getTimeRange()` and `hourUtilizationPercent` calculation
- Make a call to the `/api/third-party/first-arriving/unit-utilization` endpoint, taking note of the `unit_hour_utilization` values.
- Make another call to the same endpoint and look at the `unit_hour_utilization` values. They should change slightly as each second passes.
*To verify the time range is correct, you could drop this line in `first-arriving.controller.js` after line 78:
`Log.info('timeRange', timeRange);`*

Calculate real-time UHU for First Arriving API.

---

.eslintrc

Simplified eslint rules by using the airbnb config as the base, with a few customizations to fit the project better.
These rules aren't meant to be set in stone, since we'll probably notice things we want to adjust in the future, but they should at least be a reasonable base to build off of.
- Modified .eslintrc
To get a quick sense of how these rules would affect the codebase when applied, I would suggest enabling eslint integration with your IDE in order to see the errors/warnings that it produces. Then scan through a couple files and see if you agree with the things it complains about. Or you could run eslint from the command line for a couple files and inspect the output.

Update eslint rules.

---

email/timerange.hbs
server/api/email/email.controller.js

Hide unit summary from weekly, monthly and yearly reports
- N/A
- Added a isShift flag to description and added conditional render logic to handlebars template
-

Hide Unit Summary from weekly, monthly and yearly reports

---

email/timerange.hbs
server/api/email/email.controller.js

Reverts StatEngine/stat-engine#513

Revert "Hide Unit Summary from weekly, monthly and yearly reports"

---

client/components/shift/shift.component.html
client/components/shift/shift.component.js

Display shift differently if the name is a number or a letter
- https://app.asana.com/0/1192964035696480/1197938883939883
-
-

fix(shiftComponent): change shift display format

---

server/api/email/email.controller.js

change color to warning and update verbiage.
-
-
-

feat(email.controller): update email for no incidents

---

client/app/incident/incident-search/incident-search.controller.js

fix(incident list): times should be in dept timezone

---

email/timerange.hbs

Updated the colors of the daily report emails because it was implying the wrong sentiment. Up was bad, down was good
- https://app.asana.com/0/1177539460427774/1199114428166461
- Swapped colors
-

Swapped color of daily report up/down

---

client/app/user/user-home/index.js
client/app/user/user-home/user-home.controller.js
client/app/user/user-home/user-home.html
client/components/validation-check/validation-check.component.js
client/components/validation-check/validation-check.html
server/api/admin/admin.controller.js
server/api/admin/index.js

Added Validation health check to top of command centre for easily identifying validation errors in the data.
- https://app.asana.com/0/1177539460427774/1199636187364461
- Validation health API call
- Validation health component
- Import ES data with validation errors
- Change department to department with validation errors
- Verify

Validation Health Check

---

client/app/user/user-home/user-home.controller.js
client/components/validation-check/validation-check.component.js

- N/A
- Moved check to only check for admins to reduced wasteful queries and unnecessary latency
N/A
-

Removed unused code and only query validationHealth if global

---

client/components/validation-check/validation-check.html

Just some minor improvements
- https://app.asana.com/0/1177539460427774/1199668753094852
- Fixed text casing
- Added count to warning
- Fixed logic error
- Removed redundant html
-

Validation Health Improvements

---

client/app/workspace/workspace-edit/workspace-edit.html

On Workspace create/edit, everything was missing except for the Workspace Details. Preventing the creation or editing of Workspaces
-
-
-

fix(workspaces): fix workspace create/edit error

---

package-lock.json
package.json

chore(package json): bump shiftly version to 0.0.95

---

package-lock.json
package.json

`@statengine/shiftly` package has been updated

Bump `shiftly` to 0.0.98

---

client/app.template.html
client/app/user/help/help-home.html
package-lock.json

Remove "small chat" integrations
- Removed script to add small.chat
- Removed reference to Live chat support

Remove small chat
